#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Deploys a cloud infrastructure by using terraform and the project
https://github.com/scmschmidt/simple_deployment.

This script gets called by `dpt` and relies on the following:

- It gets called with either 'deploy' or 'destroy' as the 
  first (and only) parameter.

- The current directory contains a YAML file 'config', containing
  the infrastructure description.

- The current directory can freely used. Besides 'config' only the files
  'stdout' and 'stderr' exists and are maintained by `dtp`, which writes
  there the output of this command.

- The exit code defines, if this script was successful or not.

- Messages shall be written to stdout, errors to stderr.
  The `dtp` program will capture both and write them in to the 
  files mentioned before.

- The provider must create a YAML file called 'result' in the current
  directory, which contains the IP addresses of the deployed machines.
  The `dtp` program will process the data further.


Exitcodes:

    0   Everything went fine.
    1   Something went wrong

Ideas:
    - 
    - 

ToDo:
    - Schema needs improvement



Changelog:
----------
01.08.2022      v0.1        - and so it begins...
"""

import copy
import datetime
import hashlib
import jinja2
import os
import schema
import subprocess
import sys
import time
import random
import yaml

import pprint


VERSION = 'v0.1'
AUTHOR = 'soeren.schmidt@suse.com'


def log(text: str, level: str='info' ) -> None:
    """
    Prints the text to stdout preceded by timestamp and category. 
    """
    category = {'info': 'INFO',
                'success': ' OK ',
                'fail': 'FAIL' 
               }[level]
    print(f'[{datetime.datetime.now()}] [{category}] {text}', file=sys.stdout)

def bye(rc: int=0) -> None:
    """
    Logs termination message and exits with given exit code.
    """
    if rc == 0:
        log(f'Terminating successfully (exit code {rc}).', 'success')
    else:
        log(f'Terminating with failure (exit code {rc})!', 'fail')
    sys.exit(rc)

def load_and_vaildate(config_file: str) -> dict:
    """
    Loads the config file (YAML) into a dictionary and validates it
    against a schema afterwards.

    Terminates with error message and exit code 1 on failure.
    """

    # Load config
    try: 
        with open(config_file) as f:
            content = yaml.safe_load(f)
    except Exception as err:
        log(f'Error reading landscape: {err}', 'fail')
        bye(1)
    log(f'Landscape "{config_file}" loaded successfully.')

    # Check for an empty config.
    if not content:
        log(f'The landscape "{config_file}" is empty!', 'fail')
        bye(1)

    # Validate against schema.
    config_schema = schema.Schema({
        'build_dir': str,
        'provider_dir': str,
        'config': {

            # Azure requirement: may not contain the special characters: `\/"[]:|<>+=;,?*@&~!#$%^()_{}
            'name': schema.Regex('^[a-z.][a-z0-9.-]{1,40}$',
                                 error='"name" must be a string matching "^[a-z.][a-z0-9.-]{1,40}$".'),
            schema.Optional('admin_user'): schema.Regex('^[a-z][-a-z0-9]*$',
                                                       error='"name" must be a string matching "^[a-z.][a-z0-9.-]{1,40}$".'),
            'admin_user_key': str,
            schema.Optional('enable_root_login'): bool,
            schema.Optional('keymap'): str,
            'location': str,
            'provider': str,
            schema.Optional('provisioner'): str,
            schema.Optional('registration_server'): str,
            schema.Optional('subnet'): schema.Regex('^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[0-9]{1,2}$',
                                                    error='Must be a subnet declaration in the form: A.B.C.D/M'),
            schema.Optional('subscription_registration_key'): str,
            'hosts': [{
               'count': schema.And(int, 
                                    lambda n: True if isinstance(n, int) and n >= 1 else False,
                                    error='"count" must be an integer greater than 1'),
                schema.Optional('size'): str,
                schema.Optional('os'): str,
                schema.Optional('labels'): list
            }],
            'images': dict, # MUST BE MORE DETAILED!
            'sizing': dict  # MUST BE MORE DETAILED!
        }

    }, ignore_extra_keys=False)
    try:
        config_schema.validate(content)
    except schema.SchemaError as se:
        msgs = ['Errors during schema validation:'] 
        for err in se.errors + se.autos:
            if err:
                msgs.append(err)
        log('\n\t'.join(msgs), 'fail')
        bye(1)
    log('Schema validation passed.')

    return content

def make_plan(config: dict) -> None:
    """
    Uses config and the templates to create 
    a the terraform plan for 'simple_deployment'.
    """

    template = f'''{config['provider_dir']}/templates/main.tf.template'''
    terraform_dir = 'terraform'
    terraform_file = f'{terraform_dir}/main.tf'

    # Generate machine description.
    # To avoid unnecessary machine destruction and creation if count changes,
    # each configuration gets an id (hash of the configuration), which is used
    # in the names of the machines. 
    machine_definition = {}
    try: 
        for block in config['config']['hosts']:

            # Create the hash of the machine configuration.
            machine_config = copy.deepcopy(block) 
            del(machine_config['count'])
            hash = hashlib.blake2s(yaml.dump(machine_config).encode('utf-8'), digest_size=8).hexdigest()

            # Create a new entry, if the config is new.
            if hash not in machine_definition:
                machine_definition[hash] = { 'current': 0, 'config': machine_config, 'names': [] }
                index = 1
            
            # Add hosts.
            for index in range(machine_definition[hash]['current'], machine_definition[hash]['current']+block['count']):
                machine_definition[hash]['names'].append(f'{hash}-{index}')
            machine_definition[hash]['current'] = index + 1
    except Exception as err:
        log(f'Generating machine description failed: {err}', 'fail')
        bye(1)

    # Now we prepare a machine dict to be used by the template.
    machines = []
    for _, data in machine_definition.items():
        for name in data['names']:
            machines.append({
                'name': f'''{config['config']['name']}-{name}''',
                'size': data['config']['size'], 
                'os': data['config']['os']
            })
    config['config']['machines'] = machines

    # Fill in the template.
    try: 
        with open(template) as f:
            plan = jinja2.Template(f.read()).render(config['config'])
    except Exception as err:
        log(f'Error reading landscape: {err}', 'fail')
        bye(1)

    # Save plan.
    try:
        if not os.path.exists(terraform_dir):
            os.mkdir(terraform_dir, mode = 0o700)
        with open(terraform_file, 'w') as f:
            f.write(plan)
    except Exception as err:
        log(f'Error writing the plan file: {err}', 'fail')
        bye(1)

def write_map(config: dict, section: str, file: str) -> None:
    """
    Writes section of config into a file. 
    Either the 'default' subsection or the 'location` part is written
    into the file, depending if there is a location subsection.
    """

    try:
        location = config['config']['location']
        if location not in config['config'][section]:
            subsection = 'default'
            log(f'''Preparing "{file}": Section "{location}" not found in config, using "default".''')
        else:
            subsection = location
            log(f'''Preparing "{file}": Section "{location}" found in config.''')
            
        with open(file, 'w') as f:
            f.write(yaml.dump(config['config'][section][subsection]))
    except Exception as err:
        log(f'Error writing "{section}" to file: {err}', 'fail')
        bye(1)
    log(f'File "{file}" written.', 'success')

def terraform(command: list) -> None:
    """
    Executes the terraform command and logs stdout and stderr.
    The execution will be done in a subdirectory ``terraform``,
    which must exist and contain a ``main.tf`` file.

    The output will be logged continuously and also
    returned.  
    
    Terminates on failure.
    """ 

    terraform_dir = 'terraform'

    environment = os.environ.copy()
    environment['TF_IN_AUTOMATION'] = '1'
    
    command.insert(0, 'terraform')
    command_string = ' ' .join(command)

    output = []

    log(f'Run now "{command_string}"')
    try:
        with subprocess.Popen(command, 
                              stdout = subprocess.PIPE, 
                              stderr = subprocess.STDOUT,
                              encoding = 'utf-8',
                              cwd = terraform_dir,
                              env = environment
                             ) as proc:
            while proc.poll() is None:
                for line in proc.stdout.readlines():
                    log(f'{command_string}: {line.strip()}')  
                    output.append(line.strip())

            if proc.returncode != 0:
                raise ValueError(f'terraform exited with return code {proc.returncode}.')
                          
    except Exception as err:
        log(f'Execution of "{command_string}" failed: {err}', 'fail')
        bye(1) 

    return output     

def write_output_file(filename: str, content: str) -> None:
    """
    Writes content to file.
    """

    try: 
        with open(filename, 'w') as f:
            f.write(content)
    except Exception as err: 
        log(f'Error writing file "{filename}": {err}', 'fail')
        bye(1)
    log(f'File "{filename}" written.', 'success')

def delete(filename: str) -> None:
    """
    Simply deletes a file.
    """
    if os.path.exists(filename):
        try: 
            os.remove(filename)
        except Exception as err: 
            log(f'Error removing unused file "{filename}": {err}', 'fail')
            bye(1)
        log(f'File "{filename}" deleted.', 'success')
    else:
        log(f'File "{filename}" does not exist. nothing to delete.', 'success')

def main():

    # Print greeting.
    log(f'''Running: {' '.join(sys.argv)} (Pid: {os.getpid()})''')

    # Load and validate configuration file.
    config = load_and_vaildate('config')

    # Create terraform plan from templates.
    make_plan(config)

    # Generate/Save image and size files
    write_map(config, 'images', 'terraform/images_azure.yaml')
    write_map(config, 'sizing', 'terraform/sizing_azure.yaml')

    # Now we call terraform.
    # Recommendations for terraform options come from: 
    # https://learn.hashicorp.com/tutorials/terraform/automate-terraform?in=terraform/automation&utm_source=WEBSITE&utm_medium=WEB_IO&utm_offer=ARTICLE_PAGE&utm_content=DOCS
    
    # Executing `terraform init`.
    # WE NEED TO CHECK UPGRADE OPTION!
    terraform(['init', '-input=false'])

    # Executing `terraform plan`.
    terraform(['plan', '-input=false'])

    # Depending on the command, we apply or destroy.
    terraform([sys.argv[1], '-input=false', '-auto-approve'])

    # Create result file or ...
    if sys.argv[1] == 'apply':
        write_output_file('terraform/output.json', terraform(['output', '-json'], ))

    # ... delete result file.
    if sys.argv[1] == 'destroy':
        delete('terraform/output.json')

    print('SCHEMA MUST GET MORE DETAILS')


    # Say good bye.
    bye(0)


if __name__ == '__main__':
    main()